# Generated by Django 3.2.12 on 2022-05-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VideoManager', '0001_initial'),
        ('UserCommunication', '0001_initial'),
        ('Weblogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseRecord',
            fields=[
                ('browseTime', models.DateTimeField(auto_now_add=True)),
                ('browseDuration', models.IntegerField(default=0)),
                ('browseID', models.AutoField(primary_key=True, serialize=False)),
                ('browseUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblogin.userinfo')),
                ('browseVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoManager.videoinfo')),
                ('browseVideoPartition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserCommunication.videopartition')),
            ],
            options={
                'verbose_name': '浏览记录表',
                'verbose_name_plural': '浏览记录表',
                'db_table': 'BrowseRecord',
                'ordering': ['-browseTime'],
            },
        ),
    ]
