# Generated by Django 3.2.12 on 2022-05-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Weblogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPartition',
            fields=[
                ('videoPartName', models.CharField(max_length=30)),
                ('videoPartID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '视频分区',
                'verbose_name_plural': '视频分区',
                'db_table': 'VideoPartition',
            },
        ),
        migrations.CreateModel(
            name='UserLetter',
            fields=[
                ('letterText', models.TextField()),
                ('letterTime', models.DateTimeField(auto_now_add=True)),
                ('letterID', models.AutoField(primary_key=True, serialize=False)),
                ('letterUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ler_user', to='Weblogin.userinfo')),
                ('letteredUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='led_user', to='Weblogin.userinfo')),
            ],
            options={
                'verbose_name': '用户私信',
                'verbose_name_plural': '用户私信',
                'db_table': 'UserLetter',
                'ordering': ['-letterTime'],
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('connectID', models.AutoField(primary_key=True, serialize=False)),
                ('followedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fed_user', to='Weblogin.userinfo')),
                ('followerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fer_user', to='Weblogin.userinfo')),
            ],
            options={
                'verbose_name': '用户关注表',
                'verbose_name_plural': '用户关注表',
                'db_table': 'UserConnection',
            },
        ),
    ]
