# Generated by Django 3.2 on 2022-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCommunication', '0002_alter_userletter_letteruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userletter',
            name='letterIsRead',
            field=models.BooleanField(default=False),
        ),
    ]
