# Generated by Django 3.2.12 on 2022-05-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VideoManager', '0001_initial'),
        ('Weblogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField(max_length=500)),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentComUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cCom_user', to='Weblogin.userinfo')),
                ('commentUpUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cUp_user', to='Weblogin.userinfo')),
                ('commentVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoManager.videoinfo')),
                ('parentComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoInteraction.videocomment')),
            ],
            options={
                'verbose_name': 'VideoComment',
                'verbose_name_plural': 'VideoComment',
                'db_table': 'VideoComment',
                'ordering': ['-commentTime'],
            },
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('likeID', models.AutoField(primary_key=True, serialize=False)),
                ('likeTime', models.DateTimeField(auto_now_add=True)),
                ('likeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='Weblogin.userinfo')),
                ('likeVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoManager.videoinfo')),
                ('likedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='Weblogin.userinfo')),
            ],
            options={
                'verbose_name': '点赞记录',
                'verbose_name_plural': '点赞记录',
                'db_table': 'LikeRecord',
                'ordering': ['-likeTime'],
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('favorTime', models.DateTimeField(auto_now_add=True)),
                ('favorID', models.AutoField(primary_key=True, serialize=False)),
                ('favorUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblogin.userinfo')),
                ('favorVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoManager.videoinfo')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
                'db_table': 'Favourites',
                'ordering': ['-favorTime'],
            },
        ),
    ]
