# Generated by Django 3.2.12 on 2022-05-23 12:54

import Weblogin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('userpassword', models.CharField(max_length=128)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
                ('userInformation', models.CharField(blank=True, max_length=500)),
                ('userPortrait', models.ImageField(blank=True, upload_to=Weblogin.models.user_portrait_directory_path)),
                ('userLimit', models.BooleanField(default=False)),
                ('userSex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('userBirthday', models.DateField()),
                ('FansNum', models.IntegerField(default=0)),
                ('ConcernsNum', models.IntegerField(default=0)),
                ('TotalPlayNum', models.IntegerField(default=0)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Weblogin.userinfo')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
    ]
