# Generated by Django 3.2 on 2022-05-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userBirthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
