# Generated by Django 3.2 on 2022-05-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblogin', '0003_userinfo_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='TotalLikeNum',
            field=models.IntegerField(default=0),
        ),
    ]
