# Generated by Django 3.2.12 on 2022-05-23 12:54

import VideoManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserCommunication', '0001_initial'),
        ('Weblogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
                ('videoName', models.CharField(max_length=40)),
                ('videoInformation', models.CharField(blank=True, max_length=500)),
                ('videoPath', models.CharField(max_length=200)),
                ('videoCoverPath', models.ImageField(blank=True, upload_to=VideoManager.models.video_cover_directory_path)),
                ('videoPlayNum', models.IntegerField(default=0)),
                ('videoLikeNum', models.IntegerField(default=0)),
                ('videoFavorNum', models.IntegerField(default=0)),
                ('videoUpTime', models.DateTimeField(auto_now_add=True)),
                ('videoUpState', models.BooleanField(default=False)),
                ('videoPart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserCommunication.videopartition')),
                ('videoUpUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblogin.userinfo')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('auditTime', models.DateTimeField(auto_now_add=True)),
                ('auditResult', models.BooleanField(default=False)),
                ('auditID', models.AutoField(primary_key=True, serialize=False)),
                ('complainReason', models.CharField(max_length=400)),
                ('adminUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblogin.userinfo')),
                ('auditVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoManager.videoinfo')),
                ('complainUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_user', to='Weblogin.userinfo')),
                ('complainedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complained_user', to='Weblogin.userinfo')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'AuditRecord',
                'ordering': ['-auditTime'],
            },
        ),
    ]
