# Generated by Django 3.2.12 on 2022-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='videoCommentNum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='videoFavorNum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='videoLikeNum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='videoPlayNum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
