# Generated by Django 3.2 on 2022-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoManager', '0002_auto_20220528_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='videoPart',
            field=models.CharField(max_length=128),
        ),
    ]
