# Generated by Django 4.0.3 on 2022-05-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Weblogin', '0002_alter_userinfo_userbirthday'),
        ('VideoManager', '0003_alter_videoinfo_videopart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='adminUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Weblogin.userinfo'),
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='auditTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
