# Generated by Django 3.2 on 2022-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoManager', '0004_auto_20220530_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='videoUpState',
            field=models.BooleanField(default=True),
        ),
    ]
