# Generated by Django 4.0.3 on 2022-06-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoManager', '0004_alter_auditrecord_adminuser_and_more'),
        ('VideoManager', '0005_alter_videoinfo_videoupstate'),
    ]

    operations = [
    ]
